version: "3"
services:
  web:
    build: .
    restart: on-failure
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    #   - ./.env.secret
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/www
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
  #   depends_on:
  #     - db
  # db:
  #   image: "postgres:10.3-alpine"
  #   restart: always
  #   env_file:
  #     - ./.env.secret
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./postgres/data:/var/lib/postgresql/data