# Generated by Django 2.1.1 on 2018-11-09 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerByDockerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('port', models.CharField(max_length=20)),
                ('container_id', models.CharField(max_length=250)),
                ('container_stopped', models.CharField(max_length=1)),
                ('container_port', models.CharField(max_length=250)),
                ('container_public_port', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerByImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('port', models.CharField(max_length=20)),
                ('container_id', models.CharField(max_length=250)),
                ('container_stopped', models.CharField(max_length=1)),
                ('container_port', models.CharField(max_length=250)),
                ('container_public_port', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dockerfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_name', models.CharField(max_length=200)),
                ('dockerfile_content', models.TextField()),
                ('dockerfile', models.FileField(blank=True, upload_to='media/dockerfiles/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GitRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('last_commit_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Swarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('container_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='containerbydockerfile',
            name='dockerfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockerapp.Dockerfile'),
        ),
    ]
