# Generated by Django 2.1.1 on 2018-10-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_stopped',
            field=models.SmallIntegerField(default=1),
        ),
    ]
