# Generated by Django 2.1.1 on 2018-10-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerapp', '0002_auto_20181013_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_stopped',
            field=models.SmallIntegerField(),
        ),
    ]
